package org.i5y.json.stream;

public enum JSONEvent {
	INPUT_START, INPUT_END, OBJECT_START, OBJECT_END, PROPERTY_NAME, STRING_LITERAL, NULL_LITERAL, BOOLEAN_LITERAL, NUMBER_LITERAL, ARRAY_START, ARRAY_END, ERROR
}
